### ISSUE TITLE
[back][chat] issue on display new list channel

### ISSUE THREAD

**Issue by DaiClement** [Psycokwet/pong#200]
On listChannel change, the channel selector doesn't update properly.
To test it:
- connect with 2 accounts (with false42login for exemple),
- then go to chat,
- then go to the channel selector, 
- with the other account,
- create a public channel (with or without password),
- on the first account, 
- see missing new channel on join channel selector.

**Comment by DaiClement** [comment]
The bug appears on create and delete channel.

**Comment by DaiClement** [comment]
On reload (browser reload or react reload), the list reload so it works properly.

**Comment by DaiClement** [comment]
I mistake:
I needed a feature for websocket (need to reconnect the websocket for token).
On new websocket disconnect, the user is disconnected from all rooms (backend, default behavior of socket.io).
The user will re-connect automaticly to the room he/she was connected to.
But not to channelLobby.

There was the bug.

**Comment by Psycokwet** [comment]
closed on #201
